name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: "none"

version: 5.4.1+541

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0-nullsafety.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.0-prev2
  fancy_bottom_navigation: ^0.3.3
  firebase_core: ^1.0.1
  firebase_messaging: ^10.0.6
  flutter:
    sdk: flutter
  flutter_html: ^2.0.0-nullsafety.0
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  freezed: ^0.14.1
  get_it: ^7.2.0
  http: ^0.13.1
  image_picker: ^0.8.4
  package_info: ^2.0.0
  path_provider: ^2.0.1
  photo_view: ^0.12.0
  provider: ^6.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  upgrader: ^3.5.1
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2
  video_player: ^2.2.3

  firebase_database: ^8.0.0

  overlay_support: ^1.2.1
  agora_rtc_engine: ^4.0.1
  permission_handler: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/video/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
